spring.application.name=discografia

spring.mongodb.uri=mongodb+srv://eva2_spring:VwynNFe3Q7d8C4DV@cluster-spring.3zic83s.mongodb.net/?appName=cluster-spring
spring.mongodb.database=discografica-db
server.port=${PORT:8080}